
#pragma once
#include "math3D.h"


/** ************************************************************
 * WARNING - THIS FILE IS AUTO GENERATED by `bicubic_table.py`
 * DO NOT MODIFY THIS FILE BY HAND.
 * *************************************************************
 */

// The dimensions of the table
constexpr int NR = 51;
constexpr int NZ = 91;

// The extent of the table (in mm), as (r, z) pairs -- .x() is r, .y() is z.
// `f`-suffixed: an unsuffixed double literal here warns as a narrowing
// conversion to float, even though the value is exactly representable.
constexpr Vec2 BICUBIC_ORIGIN = { 0.0f, -20.0f };
constexpr Vec2 BICUBIC_FAR    = { 10.0f, -0.5f };

// The polarization (remanence, Br) this table was generated at. A real
// magnet is not this strong or weak -- MagnetModel divides its own
// magnet_strength_mT by this to get the ratio it scales the table by.
constexpr float BICUBIC_FIELD_REFERENCE_MT = 1000.0f;

// --- Far-field (dipole) constants, for the cross-magnet terms ---
//
// The table above covers the near model for each magnet.
// At larger distances we can fall back to a dipole model instead. The
// frame's origin is the magnet's BOTTOM FACE (see local_field.py), but the
// dipole belongs at the geometric centre -- placing it at the origin instead
// is not a small error, it is tens of percent at cross-magnet range.
constexpr float MAGNET_HALF_HEIGHT_MM = 3.0f;

// Dipole moment magnitude at BICUBIC_FIELD_REFERENCE_MT, in mT*mm^3, so it
// scales by exactly the same ratio the table does and the two models can
// never describe magnets of different strength.
//
// Units: with the moment in mT*mm^3 and distances in mm, the field
//   B = (1/4pi)(3(m.rhat)rhat - m)/rho^3
// comes out in mT with no further conversion. NOTE this is polarization x
// volume, which is NOT magpylib's `dipole_moment` property -- that one is
// SI (A*m^2) and differs from this by a factor of 1/mu0.
constexpr float DIPOLE_MOMENT_AT_REFERENCE_MT_MM3 = 169646.00329384883f;

extern const Vec2 BICUBIC_INTERPOLATION_TABLE[NZ][NR];

