"""Tests for the fitted-geometry -> firmware-constants export."""

from __future__ import annotations

import re
import struct
import zlib

import numpy as np

from calibration.bundle_geometry import (
    GROUP_SLICES,
    MAGNET_POLARITY,
    N_MAGNETS,
    N_SHARED_PARAMS,
    NOMINAL_GEOMETRY,
    BundleGeometry,
)
from calibration.export import (
    BLOB_MAGIC,
    BLOB_PAYLOAD_FLOATS,
    BLOB_SIZE,
    BLOB_VERSION,
    firmware_magnet_strength_mT,
    firmware_sensor_gain,
    firmware_sensor_offset,
    format_binary,
    format_cpp,
)
from calibration.local_field import MAGNET_POLARIZATION_MT


def _unpack_blob(blob: bytes) -> tuple[int, np.ndarray, int]:
    """Split a calibration blob the way the firmware's deserialize() does."""
    version = struct.unpack_from("<I", blob, 4)[0]
    payload = np.array(
        struct.unpack_from(f"<{BLOB_PAYLOAD_FLOATS}f", blob, 8), dtype=np.float32
    )
    crc = struct.unpack_from("<I", blob, BLOB_SIZE - 4)[0]
    return version, payload, crc


def _blob_fields(payload: np.ndarray) -> dict[str, np.ndarray]:
    """Payload floats back into named fields, in the documented order."""
    return {
        "sensor_gain": payload[0:27].reshape(3, 3, 3),
        "sensor_offset_mT": payload[27:36].reshape(3, 3),
        "magnet_pos_knob": payload[36:45].reshape(3, 3),
        "magnet_rotation": payload[45:72].reshape(3, 3, 3),
        "magnet_strength_mT": payload[72:75],
    }


def test_firmware_gain_is_the_inverse():
    """The firmware applies gain to the measurement, the fit applies it to the
    model, so the exported matrix is the inverse of the fitted one - with the
    installed magnet polarity folded back in."""
    rng = np.random.default_rng(6)
    geom = BundleGeometry.from_shared(rng.normal(0.0, 0.03, N_SHARED_PARAMS))
    fw = firmware_sensor_gain(geom)
    for i in range(3):
        assert np.allclose(fw[i] @ (MAGNET_POLARITY * geom.gain[i]), np.eye(3), atol=1e-10)


def test_nominal_gain_is_identity_and_polarity_carries_the_sign():
    """Nominal gain is +I, with the raw sensors' sign flip carried by the
    magnet's installed polarity instead. What matters is that the exported
    firmware gain still lands near -I, matching Config::magnet_gains - getting
    that sign wrong is what made the previous calibrator unfittable."""
    assert np.allclose(NOMINAL_GEOMETRY.gain, np.eye(3)[None, :, :])
    assert MAGNET_POLARITY == -1.0
    assert np.allclose(firmware_sensor_gain(NOMINAL_GEOMETRY), -np.eye(3)[None, :, :])


def test_firmware_offset_mapping():
    """o_fw = G_fw @ o_fit, i.e. the offset transforms into read_mT's space."""
    rng = np.random.default_rng(11)
    x = np.zeros(N_SHARED_PARAMS)
    x[GROUP_SLICES["sensor_offset"]] = rng.normal(0.0, 1.0, 9)
    geom = BundleGeometry.from_shared(x)
    expected = np.einsum("iab,ib->ia", firmware_sensor_gain(geom), geom.sensor_offset)
    assert np.allclose(firmware_sensor_offset(geom), expected)


def test_nominal_strength_is_local_field_polarization():
    """geometry.magnet_strength == 1.0 (nominal) means exactly
    local_field.py's own modelled polarization - so the exported mT value at
    nominal must equal that polarization's magnitude, not some other
    constant (e.g. NOT firmware/bicubic_table.py's unrelated
    BICUBIC_FIELD_REFERENCE_MT, which this function must not need to know
    about at all)."""
    assert np.allclose(NOMINAL_GEOMETRY.magnet_strength, 1.0)
    expected = abs(MAGNET_POLARIZATION_MT[2])
    assert np.allclose(firmware_magnet_strength_mT(NOMINAL_GEOMETRY), expected)


def test_strength_mT_scales_linearly_with_the_fitted_multiplier():
    """A magnet fitted at k times the nominal multiplier must report k times
    the nominal mT - the whole point of exporting a real physical unit is
    that this relationship has no hidden gauge dependence."""
    rng = np.random.default_rng(23)
    x = np.zeros(N_SHARED_PARAMS)
    x[GROUP_SLICES["magnet_strength_mean"]] = rng.normal(0.0, 0.05)
    x[GROUP_SLICES["magnet_strength_diff"]] = rng.normal(0.0, 0.02, 2)
    geom = BundleGeometry.from_shared(x)
    nominal_mt = abs(MAGNET_POLARIZATION_MT[2])
    assert np.allclose(firmware_magnet_strength_mT(geom), nominal_mt * geom.magnet_strength)


def test_format_cpp_assigns_every_calibration_params_field_once_per_magnet():
    """The snippet must assign exactly N_MAGNETS entries of each
    CalibrationParams array field - the thing that would silently break if a
    future field got added to the struct without a matching export line, or
    a copy-paste loop bug dropped a magnet."""
    rng = np.random.default_rng(31)
    geom = BundleGeometry.from_shared(rng.normal(scale=0.02, size=N_SHARED_PARAMS))
    cpp = format_cpp(geom)

    assert cpp.startswith("// ---- generated by magnet_field_model/bundle_callibration.py ----")
    assert "CalibrationParams fittedCalibration() {" in cpp
    assert cpp.rstrip().endswith("}")

    for field in (
        "sensor_gain", "sensor_offset_mT", "magnet_pos_knob",
        "magnet_rotation", "magnet_strength_mT",
    ):
        assignments = re.findall(rf"cal\.{field}\[(\d)\] = ", cpp)
        msg = f"{field}: expected {N_MAGNETS} assignments, found {assignments}"
        assert len(assignments) == N_MAGNETS, msg
        assert sorted(int(i) for i in assignments) == list(range(N_MAGNETS))


def test_format_cpp_strength_values_round_trip():
    """The printed magnet_strength_mT literals, parsed back as floats, must
    match firmware_magnet_strength_mT()'s actual values to the snippet's own
    printed precision - catches the format string and the value silently
    drifting apart (e.g. printing the wrong array, or an off-by-one index)."""
    rng = np.random.default_rng(41)
    geom = BundleGeometry.from_shared(rng.normal(scale=0.02, size=N_SHARED_PARAMS))
    cpp = format_cpp(geom)

    printed = [
        float(v) for v in
        re.findall(r"cal\.magnet_strength_mT\[\d\] = ([\-\d.]+)f;", cpp)
    ]
    assert len(printed) == N_MAGNETS
    assert np.allclose(printed, firmware_magnet_strength_mT(geom), atol=1e-5)


# --- /calibration.bin blob. The other end of this contract is
# --- firmware/include/CalibrationStorage.h; nothing but these tests checks it.


def test_crc32_matches_the_standard_check_value():
    """The firmware reimplements CRC-32 bitwise, so both ends have to agree on
    exactly which CRC-32 this is. 0xCBF43926 over b"123456789" is the published
    check value for CRC-32/ISO-HDLC (reflected, poly 0xEDB88320, init and final
    XOR 0xFFFFFFFF) - the one zlib computes. If the firmware's crc32() does not
    produce this for the same input, the two implementations are not the same
    algorithm and no stored calibration will ever validate."""
    assert zlib.crc32(b"123456789") & 0xFFFFFFFF == 0xCBF43926


def test_blob_has_the_documented_size_and_header():
    blob = format_binary(NOMINAL_GEOMETRY)
    assert len(blob) == BLOB_SIZE
    assert blob[:4] == BLOB_MAGIC == b"CMK2"
    version, payload, _ = _unpack_blob(blob)
    assert version == BLOB_VERSION
    assert payload.size == BLOB_PAYLOAD_FLOATS == 75


def test_blob_crc_covers_the_header_and_payload():
    """The CRC is over everything preceding it, not just the payload - the
    firmware checks crc32(blob, 308) against the last four bytes, so a magic or
    version corrupted in flash has to fail the checksum too."""
    blob = format_binary(NOMINAL_GEOMETRY)
    _, _, crc = _unpack_blob(blob)
    assert crc == zlib.crc32(blob[: BLOB_SIZE - 4]) & 0xFFFFFFFF


def test_corrupting_any_region_breaks_the_crc():
    blob = format_binary(NOMINAL_GEOMETRY)
    stored = struct.unpack_from("<I", blob, BLOB_SIZE - 4)[0]

    # One byte from the magic, the version, and three spread through the
    # payload - every region the checksum is supposed to be covering.
    for offset in (0, 5, 8, 150, BLOB_SIZE - 5):
        corrupted = bytearray(blob)
        corrupted[offset] ^= 0xFF
        recomputed = zlib.crc32(bytes(corrupted[: BLOB_SIZE - 4])) & 0xFFFFFFFF
        assert recomputed != stored, f"flipping byte {offset} left the CRC unchanged"


def test_blob_matrices_are_row_major():
    """Row-major is the load-bearing convention: Eigen stores Matrix3f
    column-major, so the firmware serializes through m(r, c) accessors
    specifically so this side can stay a plain .ravel(). A transposed gain
    matrix would still pass the CRC and still look plausible, so nothing
    downstream would catch it - only this test would."""
    rng = np.random.default_rng(53)
    geom = BundleGeometry.from_shared(rng.normal(scale=0.02, size=N_SHARED_PARAMS))
    _, payload, _ = _unpack_blob(format_binary(geom))

    gain = firmware_sensor_gain(geom)
    # Element [0][1] must land at index 1, where a column-major writer would
    # have put element [1][0] instead.
    assert payload[1] == np.float32(gain[0][0][1])
    assert payload[3] == np.float32(gain[0][1][0])
    # And each magnet's 9 floats are contiguous, not interleaved.
    assert np.array_equal(payload[9:18], np.asarray(gain[1], dtype=np.float32).ravel())


def test_blob_round_trips_to_the_same_numbers_format_cpp_prints():
    """The binary and text exports must be two renderings of one calibration.
    They share the firmware_* helpers, so this is really checking that the
    payload order and field slicing match what the firmware will read back."""
    rng = np.random.default_rng(67)
    geom = BundleGeometry.from_shared(rng.normal(scale=0.02, size=N_SHARED_PARAMS))
    _, payload, _ = _unpack_blob(format_binary(geom))
    fields = _blob_fields(payload)

    expected = {
        "sensor_gain": firmware_sensor_gain(geom),
        "sensor_offset_mT": firmware_sensor_offset(geom),
        "magnet_pos_knob": geom.magnet_pos_knob,
        "magnet_rotation": geom.magnet_rotation.as_matrix(),
        "magnet_strength_mT": firmware_magnet_strength_mT(geom),
    }
    for name, want in expected.items():
        # Exact, not approximate: struct.pack("<f") and np.float32 round
        # identically, so any difference here is a layout bug rather than
        # precision loss.
        assert np.array_equal(fields[name], np.asarray(want, dtype=np.float32)), name


def test_nominal_blob_is_pinned():
    """A regression pin on the whole format: the stored CRC changes if the
    layout, the field order, the version, or the nominal geometry changes. The
    first three silently break every device with a stored calibration, so they
    should not move without a version bump and a deliberate update here.

    Pinning the *stored* CRC rather than crc32 over the whole 312 bytes is
    deliberate. A message with its own CRC-32 appended always checksums to the
    residue constant 0x2144DF1C, whatever the message was, so pinning that
    would assert nothing about the content."""
    blob = format_binary(NOMINAL_GEOMETRY)
    _, _, stored = _unpack_blob(blob)
    assert stored == 0xE03758E3
    assert zlib.crc32(blob) & 0xFFFFFFFF == 0x2144DF1C  # the residue, for contrast
