"""Tests for the fitted-geometry -> firmware-constants export."""

from __future__ import annotations

import re

import numpy as np

from calibration.bundle_geometry import (
    GROUP_SLICES,
    MAGNET_POLARITY,
    N_MAGNETS,
    N_SHARED_PARAMS,
    NOMINAL_GEOMETRY,
    BundleGeometry,
)
from calibration.export import (
    firmware_magnet_strength_mT,
    firmware_sensor_gain,
    firmware_sensor_offset,
    format_cpp,
)
from calibration.local_field import MAGNET_POLARIZATION_MT


def test_firmware_gain_is_the_inverse():
    """The firmware applies gain to the measurement, the fit applies it to the
    model, so the exported matrix is the inverse of the fitted one - with the
    installed magnet polarity folded back in."""
    rng = np.random.default_rng(6)
    geom = BundleGeometry.from_shared(rng.normal(0.0, 0.03, N_SHARED_PARAMS))
    fw = firmware_sensor_gain(geom)
    for i in range(3):
        assert np.allclose(fw[i] @ (MAGNET_POLARITY * geom.gain[i]), np.eye(3), atol=1e-10)


def test_nominal_gain_is_identity_and_polarity_carries_the_sign():
    """Nominal gain is +I, with the raw sensors' sign flip carried by the
    magnet's installed polarity instead. What matters is that the exported
    firmware gain still lands near -I, matching Config::magnet_gains - getting
    that sign wrong is what made the previous calibrator unfittable."""
    assert np.allclose(NOMINAL_GEOMETRY.gain, np.eye(3)[None, :, :])
    assert MAGNET_POLARITY == -1.0
    assert np.allclose(firmware_sensor_gain(NOMINAL_GEOMETRY), -np.eye(3)[None, :, :])


def test_firmware_offset_mapping():
    """o_fw = G_fw @ o_fit, i.e. the offset transforms into read_mT's space."""
    rng = np.random.default_rng(11)
    x = np.zeros(N_SHARED_PARAMS)
    x[GROUP_SLICES["sensor_offset"]] = rng.normal(0.0, 1.0, 9)
    geom = BundleGeometry.from_shared(x)
    expected = np.einsum("iab,ib->ia", firmware_sensor_gain(geom), geom.sensor_offset)
    assert np.allclose(firmware_sensor_offset(geom), expected)


def test_nominal_strength_is_local_field_polarization():
    """geometry.magnet_strength == 1.0 (nominal) means exactly
    local_field.py's own modelled polarization - so the exported mT value at
    nominal must equal that polarization's magnitude, not some other
    constant (e.g. NOT firmware/bicubic_table.py's unrelated
    BICUBIC_FIELD_REFERENCE_MT, which this function must not need to know
    about at all)."""
    assert np.allclose(NOMINAL_GEOMETRY.magnet_strength, 1.0)
    expected = abs(MAGNET_POLARIZATION_MT[2])
    assert np.allclose(firmware_magnet_strength_mT(NOMINAL_GEOMETRY), expected)


def test_strength_mT_scales_linearly_with_the_fitted_multiplier():
    """A magnet fitted at k times the nominal multiplier must report k times
    the nominal mT - the whole point of exporting a real physical unit is
    that this relationship has no hidden gauge dependence."""
    rng = np.random.default_rng(23)
    x = np.zeros(N_SHARED_PARAMS)
    x[GROUP_SLICES["magnet_strength_mean"]] = rng.normal(0.0, 0.05)
    x[GROUP_SLICES["magnet_strength_diff"]] = rng.normal(0.0, 0.02, 2)
    geom = BundleGeometry.from_shared(x)
    nominal_mt = abs(MAGNET_POLARIZATION_MT[2])
    assert np.allclose(firmware_magnet_strength_mT(geom), nominal_mt * geom.magnet_strength)


def test_format_cpp_assigns_every_calibration_params_field_once_per_magnet():
    """The snippet must assign exactly N_MAGNETS entries of each
    CalibrationParams array field - the thing that would silently break if a
    future field got added to the struct without a matching export line, or
    a copy-paste loop bug dropped a magnet."""
    rng = np.random.default_rng(31)
    geom = BundleGeometry.from_shared(rng.normal(scale=0.02, size=N_SHARED_PARAMS))
    cpp = format_cpp(geom)

    assert cpp.startswith("// ---- generated by magnet_field_model/bundle_callibration.py ----")
    assert "CalibrationParams fittedCalibration() {" in cpp
    assert cpp.rstrip().endswith("}")

    for field in (
        "sensor_gain", "sensor_offset_mT", "magnet_pos_knob",
        "magnet_rotation", "magnet_strength_mT",
    ):
        assignments = re.findall(rf"cal\.{field}\[(\d)\] = ", cpp)
        msg = f"{field}: expected {N_MAGNETS} assignments, found {assignments}"
        assert len(assignments) == N_MAGNETS, msg
        assert sorted(int(i) for i in assignments) == list(range(N_MAGNETS))


def test_format_cpp_strength_values_round_trip():
    """The printed magnet_strength_mT literals, parsed back as floats, must
    match firmware_magnet_strength_mT()'s actual values to the snippet's own
    printed precision - catches the format string and the value silently
    drifting apart (e.g. printing the wrong array, or an off-by-one index)."""
    rng = np.random.default_rng(41)
    geom = BundleGeometry.from_shared(rng.normal(scale=0.02, size=N_SHARED_PARAMS))
    cpp = format_cpp(geom)

    printed = [
        float(v) for v in
        re.findall(r"cal\.magnet_strength_mT\[\d\] = ([\-\d.]+)f;", cpp)
    ]
    assert len(printed) == N_MAGNETS
    assert np.allclose(printed, firmware_magnet_strength_mT(geom), atol=1e-5)
