"""Turning a fitted BundleGeometry into firmware constants.

The one genuinely subtle part is the gain convention, so it is worth stating
plainly:

    This calibration applies gain to the **model**   :  pred = G_fit @ B_model
    The firmware applies gain to the **measurement** :  corrected = G_fw @ raw

Both want `corrected ~ B_model`, so **G_fw = inv(G_fit)** - the exported
matrix is the inverse of the fitted one, not the fitted one.

Fitting on the model side is deliberate. Scaling the measurement instead
would put a fitted parameter on the same side of the residual as the noise,
which lets the optimizer shrink the residual by shrinking the gain rather
than by explaining the data. Keeping the measurement untouched keeps the
residual in raw sensor units, which is exactly what ResidualWeights' sigma
model describes.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

from .bundle_geometry import MAGNET_POS_NOMINAL_KNOB, N_MAGNETS, BundleGeometry


def firmware_sensor_gain(geometry: BundleGeometry) -> NDArray[np.float64]:
    """(3, 3, 3) per-sensor gain matrices for SensorController, i.e. inv(fitted)."""
    return np.linalg.inv(geometry.gain)


def format_cpp(geometry: BundleGeometry) -> str:
    """A pasteable C++ snippet with the fitted constants.

    Deliberately just text: this firmware has no persistence layer of any kind
    yet, so a generated snippet the user can paste (and diff) is the honest
    delivery mechanism until one exists.
    """
    gain = firmware_sensor_gain(geometry)
    pos = geometry.magnet_pos_knob
    rot = geometry.magnet_rotation.as_matrix()
    off = pos - MAGNET_POS_NOMINAL_KNOB

    def mat3(m: NDArray[np.float64], indent: str) -> str:
        rows = ",\n".join(
            indent + "  " + ", ".join(f"{v: .6f}f" for v in row) for row in m
        )
        return "(Mat3() <<\n" + rows + "\n" + indent + ").finished()"

    lines = [
        "// ---- generated by magnet_field_model/bundle_callibration.py ----",
        "// Per-sensor gain applied to the RAW reading in SensorController.",
        "// (inverse of the fitted model-side gain - see calibration/export.py)",
        "inline const Mat3 sensor_gain[3] = {",
    ]
    for i in range(N_MAGNETS):
        lines.append("    " + mat3(gain[i], "    ") + ("," if i < 2 else ""))
    lines.append("};")
    lines.append("")
    lines.append("// Knob-frame magnet positions (BOTTOM-FACE reference, as in positions.h).")
    lines.append("// Offsets from nominal: " + ", ".join(
        f"[{o[0]:+.3f} {o[1]:+.3f} {o[2]:+.3f}]" for o in off))
    for i in range(N_MAGNETS):
        lines.append(
            f"inline const Vec3 Magnet_{i + 1}_knob = {{ "
            f"{pos[i][0]: .6f}f, {pos[i][1]: .6f}f, {pos[i][2]: .6f}f }};"
        )
    lines.append("")
    lines.append("// Per-magnet axis tilt (knob frame).")
    lines.append("inline const Mat3 magnet_rotation[3] = {")
    for i in range(N_MAGNETS):
        lines.append("    " + mat3(rot[i], "    ") + ("," if i < 2 else ""))
    lines.append("};")
    return "\n".join(lines)
