#!/usr/bin/env python3
"""Embed one real calibration run as a C++ header for the on-device harness.

    ./generate_calibration_frames.py [run.json] [n_frames] > calibration_frames_data.h

The harness needs real captured readings, not model-generated ones. Synthetic
frames make the solver fit its own predictions, which is the easiest possible
case: no sensor noise, no model mismatch, no unmodelled cross-magnet term, and
a data residual that can reach exactly zero. Timing is representative either
way, but convergence behaviour is not.

Emits only the raw 9-float readings per frame. Poses are deliberately NOT
emitted: the device seeds them itself by running solve_knob_pose against
nominal geometry, exactly as calibration_algorithm.py does before its joint
solve. That is part of what an on-device calibration would actually cost, so
it belongs inside the measurement rather than baked into a constant.

Frames are decimated evenly across the whole run, matching
calibration_algorithm.py's _decimate(), so the selection spans every motion
pattern rather than truncating to the first few.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

DEFAULT_RUN = Path(__file__).resolve().parents[3] / "magnet_field_model" / \
    "calibration_runs" / "raw_20260730_232737.json"
DEFAULT_N = 60


def main() -> int:
    run_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_RUN
    n_frames = int(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_N

    raw = json.loads(run_path.read_text())

    # Patterns in a stable order, so regenerating the same run gives the same
    # header. Empty groups (COMPLETE is often unused) drop out.
    frames: list[tuple[str, list[float]]] = []
    for name in sorted(raw):
        for row in raw[name]:
            if len(row) != 9:
                raise SystemExit(f"{name}: expected 9 readings per frame, got {len(row)}")
            frames.append((name, row))

    if not frames:
        raise SystemExit(f"{run_path}: no frames")

    # Even decimation across the whole run -- mirrors _decimate() in
    # calibration_algorithm.py.
    if len(frames) > n_frames:
        step = (len(frames) - 1) / (n_frames - 1) if n_frames > 1 else 0
        picked = [frames[round(i * step)] for i in range(n_frames)]
    else:
        picked = frames

    counts: dict[str, int] = {}
    for name, _ in picked:
        counts[name] = counts.get(name, 0) + 1

    out = sys.stdout
    out.write("// GENERATED by generate_calibration_frames.py -- do not edit.\n")
    out.write(f"//\n// Source: {run_path.name}\n")
    out.write(f"// {len(frames)} frames in the run, decimated evenly to {len(picked)}.\n")
    out.write("// Frames per motion pattern in this selection:\n")
    for name in sorted(counts):
        out.write(f"//   {name:<14} {counts[name]}\n")
    out.write("//\n")
    out.write("// Raw sensor readings in mT, 3 sensors x 3 axes per frame, exactly as\n")
    out.write("// captured. No poses: the device seeds those itself with solve_knob_pose\n")
    out.write("// against nominal geometry, the same way calibration_algorithm.py does.\n")
    out.write("#pragma once\n\n")
    out.write(f"static constexpr int CALIBRATION_RUN_FRAMES = {len(picked)};\n\n")
    out.write("static const float CALIBRATION_RUN_READINGS[CALIBRATION_RUN_FRAMES][9] = {\n")
    for name, row in picked:
        vals = ", ".join(f"{v:>12.6f}f" for v in row)
        out.write(f"    {{{vals}}},   // {name}\n")
    out.write("};\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
